// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNoteToDB(arg1:string):Promise<void>;

export function DeleteNoteFromDB(arg1:number):Promise<void>;

export function EditNoteToDB(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetDB():Promise<string>;

export function GetKey(arg1:string):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;
