// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNoteToDB(arg1) {
  return window['go']['main']['App']['AddNoteToDB'](arg1);
}

export function DeleteNoteFromDB(arg1) {
  return window['go']['main']['App']['DeleteNoteFromDB'](arg1);
}

export function EditNoteToDB(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditNoteToDB'](arg1, arg2, arg3);
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function GetKey(arg1) {
  return window['go']['main']['App']['GetKey'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
